# Audio
#BOARD_USES_LEGACY_ALSA_AUDIO := true
AUDIO_FEATURE_ENABLED_LOW_LATENCY_CAPTURE := true
BOARD_USES_ALSA_AUDIO := true
TARGET_TINY_ALSA_IGNORE_SILENCE_SIZE := true
# Disable the very verbose audio hal
TARGET_AUDIO_DISABLE_LOGS := true

# Marvell flags
BOARD_WITH_ACOUSTIC := true
BOARD_WITH_TELEPHONY_AUDIO := true
BOARD_ENABLE_ADVANCED_AUDIO := true
BOARD_AUDIO_COMPONENT_APU := MAP-LITE

# Set this to true when its working
#BOARD_WITH_MRVL_AEC_AUDIO := true
