# Display & Graphics
USE_OPENGL_RENDERER := true
ANDROID_ENABLE_RENDERSCRIPT := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
BOARD_EGL_CFG := $(COMMON_PATH)/configs/egl/egl.cfg

BOARD_EGL_NEEDS_HANDLE_VALUE := true

BOARD_ENABLE_OVERLAY := true
BOARD_GRAPHICS_ENABLE_3D := true
