LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := rtccd3
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE := rtccd3
LOCAL_MODULE_TAGS := optional

include $(BUILD_PREBUILT)
